name: Deploy PEP Data Pipeline to AWS

# This workflow triggers automatically on any push to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      #Check out the code from your repository.
      - name: Checkout repository
        uses: actions/checkout@v3

      #Set up Python, we'll need for packaging.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      #Set up Terraform.
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      #Configure AWS credentials using the secrets we stored.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Or your chosen region

      # Package each Lambda function with its dependencies.
      # For each function, we go into its directory,
      # install its requirements into a 'package' folder, and then zip
      # both the code and the libraries together.

      - name: Package Lambda Functions
        run: |
          # Package lambda_data_simulation
          pip install -r src/lambda_data_simulation/requirements.txt -t src/lambda_data_simulation/package
          cd src/lambda_data_simulation
          zip -r deploy.zip .
          cd ../..

          # Package lambda_data_processing
          pip install -r src/lambda_data_processing/requirements.txt -t src/lambda_data_processing/package
          cd src/lambda_data_processing
          zip -r deploy.zip .
          cd ../..

          # Package lambda_api
          pip install -r src/lambda_api/requirements.txt -t src/lambda_api/package
          cd src/lambda_api
          zip -r deploy.zip .
          cd ../..

      #Run Terraform to deploy the infrastructure and new code.
      - name: Terraform Deploy
        working-directory: ./terraform
        run: |
          terraform init
          terraform apply -auto-approve
      # Upload the deployment packages as artifacts just for testing purpose.
      - name: Upload Lambda Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-packages
          path: |
            src/lambda_data_simulation/deploy.zip
            src/lambda_data_processing/deploy.zip
            src/lambda_api/deploy.zip